### ISSUE TITLE
errors need to be logged.

### ISSUE THREAD

**Issue by dvc94ch** [Nuhvi/mainline#6]
currently a coworker of mine is experiencing trouble with the dht. it works fine on my machine but not on his. without any logs, it's hard to tell what might be the cause. looks like the socket for example just swallows any errors.

**Comment by Nuhvi** [comment]
Ok, I was hesitant to add any tracing because it is not without cost. But now I have a real-world request.

Do you have a preferred way to do it? `tracing`? or simply `eprintln!()`?

**Comment by dvc94ch** [comment]
`tracing` or `log` work. I don't think logging using eprintln is very common. And filtering logs by crate and level is really useful when you have a large rust project.
